# This file was generated by GoReleaser. DO NOT EDIT.
cask "svg2drawio" do
  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "37636c20231d54e6e6eedb14431966726b987b09f5129d09819c134560772116"
      url "https://github.com/bcollard/svg2drawio/releases/download/v#{version}/svg2drawio_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "320e3d8699da661a223b8820ab9b5474422cbca3e618234d16252d2914f6c936"
      url "https://github.com/bcollard/svg2drawio/releases/download/v#{version}/svg2drawio_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "941f11e8e04389c6f89cf5674ae5c4ba26b330a487c0520bfd30391f067a82e4"
      url "https://github.com/bcollard/svg2drawio/releases/download/v#{version}/svg2drawio_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6f83dd1694fed6cafb67fdb270eb1b4c404b349533a69a118708ebb2904396f3"
      url "https://github.com/bcollard/svg2drawio/releases/download/v#{version}/svg2drawio_#{version}_linux_amd64.tar.gz"
    end
  end

  name "svg2drawio"
  desc "Convert SVG files into native draw.io (mxGraph) diagrams"
  homepage "https://svg2drawio.runlocal.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "svg2drawio"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/svg2drawio"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Agent Skill: teach your AI coding tool to drive svg2drawio with

      svg2drawio skill install
  EOS
end
